version: '3.7'
services:
   sisk-app:
      container_name: 'sisk-app'
      build: ./
      ports:
         - '3000:3000'
      volumes:
         - '/app/node_modules'
         - '.:/app'
      stdin_open: true
