// MIB EMAEMALJS DATA
const USER_MIB_SERVICE_ID = 'service_37tym6s';
const USER_MIB_TEMPLATE_MESSAGE_ID = 'template_730331f';
const USER_MIB_TEMPLATE_EMPLOYEE_ID = 'template_izso2cm';
const USER_MIB_ID = 'F5GQ2uMSxv5uJlqal';

// SISK EMALJS DATA
const USER_SERVICE_ID = 'service_z83jspu';
const USER_TEMPLATE_BOOKING_ID = 'template_gsvb2al';
const ADMIN_TEMPLATE_BOOKING_ID = 'template_5l7nfa5';
const USER_ID = 'WVZmIS-yZPys5LkVr';

export {
   USER_SERVICE_ID,
   ADMIN_TEMPLATE_BOOKING_ID,
   USER_TEMPLATE_BOOKING_ID,
   USER_ID,
   USER_MIB_TEMPLATE_MESSAGE_ID,
   USER_MIB_TEMPLATE_EMPLOYEE_ID,
   USER_MIB_SERVICE_ID,
   USER_MIB_ID
};
