enum SAVING_STAGE {
  SUCCESS = 'SUCCESS',
  INITIAL = 'INITIAL',
  ERROR = 'ERROR'
}

enum MODAL_STATE {
  INITIAL = 'INITIAL',
  DISPLAY = 'DISPLAY'
}

enum LOGIN_STATE {
  LOG_IN = 'LOG_IN',
  LOG_OUT = 'LOG_OUT'
}

enum MODAL_TYPES {
  EMPTY = 'EMPTY',
  MESSAGE = 'MESSAGE',
  RESERVATION = 'RESERVATION',
  CONFIRM = 'CONFIRM'
}

enum USER_STATE {
  GET = 'GET',
  ERROR = 'ERROR'
}

enum COLLECTION_STATE {
  GET = 'GET',
  UPDATE = 'UPDATE',
  ADD = 'ADD',
  DELETE = 'DELETE',
  ERROR = 'ERROR'
}

export { MODAL_STATE, MODAL_TYPES, SAVING_STAGE, USER_STATE, LOGIN_STATE, COLLECTION_STATE };
