export const SAVING_STAGE = {
  SUCCESS: 'SUCCESS',
  INITIAL: 'INITIAL',
  ERROR: 'ERROR',
};

export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';

export const GET_USER = 'GET_USERS';
export const ERROR_USER = 'ERROR_USERS';

export const GET_CLIENTS = 'GET_CLIENTS';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const ADD_CLIENT = 'ADD_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const ERROR_CLIENT = 'ERROR_CLIENT';

export const GET_BUILDINGS = 'GET_BUILDINGS';
export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS';
export const ADD_BUILDINGS = 'ADD_BUILDINGS';
export const DELETE_BUILDINGS = 'DELETE_BUILDINGS';
export const ERROR_BUILDINGS = 'ERROR_BUILDINGS';

export const GET_BOOKINGS = 'GET_BOOKING';
export const GET_SINGLE_BOOKING = 'GET_SINGLE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const ADD_BOOKING = 'ADD_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const ERROR_BOOKING = 'ERROR_BOOKING';
